---
- name: prepare | install awscli via snap
  community.general.snap:
    name: aws-cli
    classic: true

- name: prepare | get aws cli path
  command: which aws
  register: aws_cli_path
  changed_when: false
  failed_when: aws_cli_path.rc != 0

- name: prepare | aws symlink
  file:
    src: "{{ aws_cli_path.stdout }}"
    dest: /usr/bin/aws
    state: link
  when: aws_cli_path.stdout != "/usr/bin/aws"

- name: prepare | ensure AWS config directory exists
  ansible.builtin.file:
    path: "~/.aws"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0700"
  become: true
  become_user: "{{ item }}"
  loop:
    - '{{ postgresql_user }}'
    - root

- name: prepare | configure AWS config for each backup set
  ansible.builtin.template:
    src: aws_config.j2
    dest: "~/.aws/config"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0600"
  become: true
  become_user: "{{ item }}"
  loop:
    - '{{ postgresql_user }}'
    - root

- name: prepare | configure AWS credentials for each backup set
  ansible.builtin.template:
    src: aws_credentials.j2
    dest: "~/.aws/credentials"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0600"
  no_log: true
  become: true
  become_user: "{{ item }}"
  loop:
    - '{{ postgresql_user }}'
    - root
