---
- name: override tmp_jobs to null
  set_fact:
    tmp_jobs:

- name: prepare | creates a cron cluster backup
  set_fact:
    cron_pure: "{{ item.cron }}"
    cron_extra:
      job: "{{ postgresql_job_backup_cluster }} -PostgresqlUser {{ item.cluster.user }} -PostgresqlHost {{ item.cluster.host }} -PostgresqlPort {{ item.cluster.port }} -BackupFolder {{ item.cluster.backupFolder }} -TestArchive \\${{ item.cluster.testArchive | default(true) }} "
      name: "Backup-{{ item.name }}"
      cron_file: postgres_backup
      tag: "{{ item.tag | default('CRON_PSQL_BACKUP') }}"
  with_items: "{{ postgres_backup.backup_cluster_sets }}"
  register: tmp_jobs
  when:
    - postgres_backup.backup_cluster_sets is defined
    - item.cron is defined
    - item.cluster is defined

- import_tasks: cron_jobs_prepare.yml

# -----------------

- name: override tmp_jobs to null
  set_fact:
    tmp_jobs:

- name: prepare | creates a cron dump backup file under /etc/cron.d
  set_fact:
    cron_pure: "{{ item.cron }}"
    cron_extra:
      job: "{{ postgresql_job_backup_db }}
        -Database {{ item.dump.database }}
        -PostgresqlUser {{ item.dump.user }}
        -PostgresqlPassword {{ item.dump.password }}
        -PostgresqlHost {{ item.dump.host }}
        -PostgresqlPort {{ item.dump.port }}
        -BackupFolder {{ item.dump.backupFolder }}
        -s3Profile {{ item.dump.s3Profile | default ('\\$null') }}
        -s3Endpoint {{ item.dump.s3Endpoint | default ('\\$null') }}"
      name: "Backup-{{ item.name }}"
      cron_file: postgres_backup
      tag: "{{ item.tag | default('CRON_PSQL_BACKUP') }}"
  with_items: "{{ postgres_backup.backup_sets }}"
  register: tmp_jobs
  when:
    - postgres_backup.backup_sets is defined
    - item.cron is defined
    - item.dump is defined

- import_tasks: cron_jobs_prepare.yml