---
- name: prepare | dependencies
  apt:
    update_cache: yes
    name:
      - p7zip-full
      - snapd

- name: prepare | snap powershell
  community.general.snap:
    name:
      - powershell
    classic: true

- name: prepare | copy PS scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u+rwx,g=rx,o=rx
  with_items:
    - { src: postgre_wal_read.ps1, dest: /usr/local/bin/postgre_wal_read.ps1 }
    - { src: postgre_wal_write.ps1, dest: /usr/local/bin/postgre_wal_write.ps1 }
    - { src: postgre_backup_cluster.ps1, dest: /usr/local/bin/postgre_backup_cluster.ps1 }
    - { src: postgre_dump_db.ps1, dest: /usr/local/bin/postgre_dump_db.ps1 }
    - { src: Remove-Backup.ps1, dest: /usr/local/bin/Remove-Backup.ps1 }
