---
- name: prepare | creates a cron cleanup task
  set_fact:
    cron_pure: "{{ cleanup.cron }}"
    cron_extra:
      job: "{{ postgresql_job_cleanup }} -BackupFolder {{ item.cleanup_folder }} -Days {{ item.days }} -SaveEachMonthDay {{ item.save_each_month_day | default('$null') }} 2>&1"
      name: "cleanup_{{ item.name }}"
      cron_file: cleanup 
  with_items: "{{ cleanup.cron.folder }}"
  register: tmp_jobs

- import_tasks: cron_jobs_prepare.yml
