---
- name: Configure postgresql.conf
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql

- block:
  - name: Combine recovery.conf settings
    set_fact:
      recovery_conf:
        restore_command: "{{ postgresql_global_config_options.restore_command }}"
        standby_mode: 'on'
        primary_conninfo: "{{ postgresql_global_config_options.primary_conninfo }}"
        trigger_file: "{{ postgresql_global_config_options.promote_trigger_file }}"

  - name: Configure recovery.conf for pg 9.6
    template:
      src: "recovery.conf.j2"
      dest: "{{ postgresql_data_dir }}/recovery.conf"
      owner: "{{ postgresql_user }}"
      group: "{{ postgresql_group }}"
      mode: 0600
    notify: restart postgresql

  when: postgresql_role == 'secondary' and postgresql_version == '9.6'

- name: Add password to .pgpass for postgresql_user
  lineinfile:
    line: "{{ postgresql_primary.host }}:{{ postgresql_primary.port }}:replication:{{ postgresql_primary.user }}:{{ postgresql_primary.password }}"
    regexp: "{{ postgresql_primary.host }}:{{ postgresql_primary.port }}:replication:{{ postgresql_primary.user }}"
    dest: "{{ postgresql_home_dir }}/.pgpass"
    create: yes
    mode: 0600
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
  when: postgresql_primary is defined

- name: Configure host based authentication (if entries are configured).
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries | length > 0

- name: Ensure PostgreSQL unix socket dirs exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "{{ postgresql_unix_socket_directories_mode }}"
  with_items: "{{ postgresql_unix_socket_directories }}"
