---
- block:
  - name: Template sql script /tmp/ansible-postgre-script.sql
    template: 
      src: script.sql.j2
      dest: /tmp/ansible-postgre-script.sql

  - name: Execute sql script {{ postgresql_scripts_item.name }} against {{ postgresql_scripts_item.db }} 
    shell: "sudo -u {{ postgresql_user }} psql --dbname={{ postgresql_scripts_item.db }} --echo-all --file=/tmp/ansible-postgre-script.sql"

  - name: Delete sql script /tmp/ansible-postgre-script.sql
    file: 
      path: /tmp/ansible-postgre-script.sql
      state: absent

