---
- block:
  - name: Template sql script {{ postgres_temp_template_script_path }}
    template: 
      src: script.sql.j2
      dest: "{{ postgres_temp_template_script_path }}"

  - name: Execute sql script {{ postgresql_scripts_item.name }} against {{ postgresql_scripts_item.db }} 
    shell: "sudo -u {{ postgresql_user }} psql --dbname={{ postgresql_scripts_item.db }} --echo-all --file={{ postgres_temp_template_script_path }}"
    register: psqlout

  - name: Output {{ postgresql_scripts_item.name }} against {{ postgresql_scripts_item.db }}
    debug:
      msg: "{{ psqlout.stdout }}"


