---
# Variable configuration.
- include_tasks: variables.yml

- include_tasks: backup.yml

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: initialize.yml

- block:
  - include_tasks: cluster_initialize.yml
    when: not pgdata_dir_version.stat.exists
  - include_tasks: configure.yml
  - include_tasks: service.yml
  - import_tasks: users.yml
  - import_tasks: databases.yml
  - import_tasks: users_props.yml
  when: postgresql_role == 'primary'

- block:
  - include_tasks: cluster_copy.yml
    when: not pgdata_dir_version.stat.exists
  - include_tasks: configure.yml
  - include_tasks: service.yml
  when: postgresql_role == 'secondary'

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"