---
- import_tasks: setup-Debian-repo.yml
  when: ansible_os_family == 'Debian'

- name: prepare | PostgreSQL client dependencies
  apt:
    name: "postgresql-client-{{ postgresql_version }}"
    state: present
  when: ansible_os_family == 'Debian'

- name: prepare | PostgreSQL client dependencies
  ansible.builtin.package:
    name: "postgresql{{ postgresql_version }}"
  when: ansible_os_family == 'RedHat'
  ignore_errors: true
