---
- name: prepare | snapd
  ansible.builtin.package:
    name:
      - snapd

- name: prepare | enable snapd.socket
  systemd:
    name: snapd.socket
    state: started
    enabled: yes
    daemon_reload: yes
  when: ansible_os_family == 'RedHat'

- name: prepare | snap symlink
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: ansible_os_family == 'RedHat'

- name: prepare | snap powershell
  community.general.snap:
    name:
      - powershell
    classic: true