---
- name: Ensure {{ postgres_cron_template_script_path }} directory exists.
  file:
    path: "{{ postgres_cron_template_script_path }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: directory
    mode: 0700

- name: prepare | creates a sql scripts for cron
  template: 
    src: cron_script.sql.j2
    dest: "{{ postgres_cron_template_script_path }}/{{ item.name }}.sql"
    owner: "{{ postgresql_user }}"
    mode: '0755'
  with_items: "{{ postgresql_cronjob_scripts }}"
  when:
    - postgresql_cronjob_scripts is defined
    - item.script is defined
    - item.db is defined
    - item.cron is defined

- name: set list of tasks sql cron
  set_fact:
    listsql_for_cron_role: "{{ [ item.cron | combine ({'job': simple_job })] + listsql_for_cron_role | default ([]) }}"
  vars:
    simple_job: "psql --no-psqlrc --variable=ON_ERROR_STOP=1 --dbname={{item.db}}  --file={{ postgres_cron_template_script_path }}/{{ item.name }}.sql 2>&1"
  with_items: "{{ postgresql_cronjob_scripts }}"

#import role from https://github.com/apavlov-agro/ansible_role_cron.git
- name: Crontab jobs
  import_role:
    name: ../../../linux/role_cron
  vars:
    cron_tasks: "{{ listsql_for_cron_role }}"
  when:
    - postgresql_cronjob_scripts is defined

