---
- name: Ensure PostgreSQL users are configured correctly
  include_tasks: user_props.yml
  loop_control:
     loop_var: postgresql_user_item
  with_items: "{{ postgresql_users }}"
  no_log: "{{ postgres_users_no_log }}"
  # See: https://github.com/ansible/ansible/issues/16048#issuecomment-229012509
  vars:
    ansible_ssh_pipelining: true  