---
- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5


- name: reload postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: "reloaded"
    sleep: 5
